# Generated by Django 4.0 on 2023-05-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='cv',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
